"""Disaster simulation run and simulation results models."""

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, List, Optional
from sqlalchemy import Float, String, ForeignKey, DateTime
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.knowledge import DecisionKnowledge


class Simulation(Base):
    """Disaster scenario simulation execution metadata."""

    __tablename__ = "simulations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(String(500), default="", nullable=False)

    # Input parameters stored in JSON (rainfall_mm, dam_release, river_level, traffic_multiplier)
    input_parameters: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)

    status: Mapped[str] = mapped_column(
        String(50), default="PENDING", nullable=False, index=True
    )  # PENDING, RUNNING, COMPLETED, FAILED

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True
    )

    # Relationships
    results: Mapped[List["SimulationResult"]] = relationship(
        "SimulationResult", back_populates="simulation", cascade="all, delete-orphan"
    )
    knowledge_entries: Mapped[List["DecisionKnowledge"]] = relationship(
        "DecisionKnowledge", back_populates="simulation", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Simulation {self.name} [{self.status}]>"


class SimulationResult(Base):
    """Output metrics and predictions generated by a simulation run."""

    __tablename__ = "simulation_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    simulation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("simulations.id", ondelete="CASCADE"), nullable=False
    )

    flood_spread_data: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    recommended_evacuation_plan: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    recommended_resource_plan: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)

    effectiveness_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)  # 0.0 to 100.0
    ai_confidence_pct: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    simulation: Mapped["Simulation"] = relationship("Simulation", back_populates="results")

    def __repr__(self) -> str:
        return f"<SimulationResult for Sim {self.simulation_id} - Score: {self.effectiveness_score}>"
